#!/bin/bash -eux
set -o pipefail


# Globals
PROCESS_NAME=elastic-agent
LOG_DIR="/var/vcap/sys/log/${PROCESS_NAME}"
SCRIPT_NAME="${PROCESS_NAME}_ctl"
PKG_DIR="/var/vcap/packages/${PROCESS_NAME}"
AGENT_PROGRAM_DIR=/opt/Elastic/Agent
BOSH_CONFIG_DIR="/var/vcap/jobs/${PROCESS_NAME}/config"


source "/var/vcap/jobs/${PROCESS_NAME}/bin/functions/common.sh"

function add_systemd_override() {
    local override_directory="/etc/systemd/system/${PROCESS_NAME}.service.d"

    mkdir -pv "${override_directory}"
    cp -v "${BOSH_CONFIG_DIR}/override.conf" "${override_directory}"
    systemctl daemon-reload
}

function start() {
    systemctl is-active elastic-agent && exit 0

    overwrite_agent_config "${BOSH_CONFIG_DIR}" "${AGENT_PROGRAM_DIR}"
    process_path=$(readlink -f "${PKG_DIR}/bin/${PROCESS_NAME}")
    setcap cap_net_bind_service=+ep "${process_path}"

    add_systemd_override
    systemctl is-enabled "${PROCESS_NAME}" --quiet || systemctl enable "${PROCESS_NAME}" \
    1>> "${LOG_DIR}/${PROCESS_NAME}.stdout.log" \
    2>> "${LOG_DIR}/${PROCESS_NAME}.stderr.log" &

    systemctl start "${PROCESS_NAME}" \
    1>> "${LOG_DIR}/${PROCESS_NAME}.stdout.log" \
    2>> "${LOG_DIR}/${PROCESS_NAME}.stderr.log" &
}

function stop() {
    systemctl stop "${PROCESS_NAME}"
}

function main() {
    local operation="${1:-null}"
    mkdir -pv "${LOG_DIR}"
    start_logging "${LOG_DIR}" "${SCRIPT_NAME}"
    case ${operation} in
        start)
            start
        ;;
        stop)
            stop
        ;;
        *)
            echo "Usage: ${0} {start|stop}"
        ;;
    esac
}


main $@