---
releases:
- name: elastic-agent
  version: 1.0.0

addons:
- name: elastic-agent
  jobs:
  - name: elastic-agent
    release: elastic-agent
    properties:
      fleet:
        enrollment_token: bUFacmtZc0JpU0hGNXk2cXZxUG86Ymg2OVFzTXhUN3VCbXBmSVZWMUx2dw==
        url: https://9fbd28e908184eb3b2292a0de33a698a.fleet.us-east4.gcp.elastic-cloud.com
      tags:
      - sandbox
      - cloudfoundry
    exclude:
      deployments:
      - bosh-health
    include:
      lifecycle: service
      stemcell:
      - os: ubuntu-xenial
      - os: ubuntu-jammy